/**
 * Media registry.
 *
 * Optional real-footage slots (drop the files in, no code changes needed):
 *   public/video/hero.mp4  -> replaces the procedural sky film in Act 1
 *   public/video/door.mp4  -> replaces the cobalt rift with a video doorway
 *
 * When a file is missing the site automatically falls back to its procedural
 * visuals (SkyFilm canvas, CSS clouds, scroll rift) — nothing breaks.
 */

export const HERO_MP4 = "/video/hero.mp4";
export const DOOR_MP4 = "/video/door.mp4";

/** Studio-showcase portrait pair (cursor spotlight reveal). */
export const STUDIO_BASE = "/media/studio-base.png";
export const STUDIO_REVEAL = "/media/studio-reveal.png";

/** Harvested screenshots of past projects (generated by `npm run harvest`). */
export const AURA_SHOTS = [
  "/media/aura-1.jpg",
  "/media/aura-2.jpg",
  "/media/aura-3.jpg",
  "/media/aura-4.jpg",
];

export const AXIOM_SHOTS = [
  "/media/axiom-1.jpg",
  "/media/axiom-2.jpg",
  "/media/axiom-3.jpg",
  "/media/axiom-4.jpg",
];
